# Generated by Django 5.0.6 on 2024-06-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mascotas',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='infousuarios',
            name='mascotas',
            field=models.ManyToManyField(related_name='dueños', to='Core.mascotas'),
        ),
    ]
