# Generated by Django 5.0.6 on 2024-06-24 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_mascotas_options_infousuarios_mascotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascotas',
            name='id_colormascota',
            field=models.ForeignKey(blank=True, db_column='id_colormascota', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.tiposcolormascotas'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='id_tipomascota',
            field=models.ForeignKey(blank=True, db_column='id_tipomascota', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.tiposmascotas'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='id_tiporaza',
            field=models.ForeignKey(blank=True, db_column='id_tiporaza', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.tiposrazasmascotas'),
        ),
        migrations.AddField(
            model_name='mascotas',
            name='id_tiposangremascota',
            field=models.ForeignKey(blank=True, db_column='id_tiposangremascota', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Core.tipossangremascotas'),
        ),
    ]
