# Generated by Django 5.0.6 on 2024-06-25 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='adopcion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.adopcion'),
            preserve_default=False,
        ),
    ]
