# Generated by Django 5.0.6 on 2024-06-25 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_notificacion_adopcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacion',
            name='adopcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.adopcion'),
        ),
    ]
