# Generated by Django 5.0.6 on 2024-06-25 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_notificacion_adopcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopcion',
            name='mascota',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.mascotas'),
            preserve_default=False,
        ),
    ]
