# Generated by Django 5.0.6 on 2024-06-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
